# Generated by Django 4.2.5 on 2023-09-29 02:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('requires_management', models.BooleanField(default=False)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventtype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventstatus')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
